import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../src/shared/components/Header";
import { TaskProvider } from "shared/TaskProvider/TaskProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col  items-center h-screen`}
      >
        <Header />
        <div className="flex flex-col w-full md:w-[736px] mx-auto h-screen items-center px-4">
          {/* <div className="flex flex-col w-[736px] mx-auto"> */}
          <TaskProvider>{children}</TaskProvider>
        </div>
      </body>
    </html>
  );
}
